name: quran_rec
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  audioplayers: ^6.4.0
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  record: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/quran-uthmani.json

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/Amiri-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Amiri-Italic.ttf
          style: italic
